# Generated by Django 5.0 on 2023-12-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daifuwu", "0002_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="openid",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
