# Generated by Django 5.0 on 2023-12-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daifuwu", "0003_customuser_openid"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="ex_phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
