# Generated by Django 5.0 on 2023-12-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daifuwu", "0004_task_ex_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
