# Generated by Django 5.0 on 2023-12-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daifuwu", "0007_taskmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmessage",
            name="sender",
            field=models.CharField(
                choices=[("creator", "Creator"), ("assignee", "Assignee")],
                max_length=20,
            ),
        ),
    ]
