# Generated by Django 5.0 on 2023-12-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daifuwu", "0009_alter_taskmessage_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="last_chat_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
