# Generated by Django 5.0 on 2023-12-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daifuwu", "0010_task_last_chat_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="please",
            field=models.BooleanField(default=False),
        ),
    ]
